stages:
  - deploy
  - ci_status

include:
  - project: telios2/telios-devops
    ref: master 
    file: ".gitlab-ci.DiscordWebhook.yml"

image: node:latest

# allow caching for faster deployment
cache:
  paths:
    - node_modules/
    - public/
    - .cache/

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build:gitlab
  artifacts:
    paths:
      - public
  only:
    - master
